{% set name = "stackview" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stackview-{{ version }}.tar.gz
  sha256: 64b6568a9f9a2c9b8e827cc03df313823c77543bdaa8f20e638e41b99a95184c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numpy
    - python >=3.7
    - ipycanvas
    - ipywidgets
    - scikit-image
    - ipyevents
    - toolz
    - matplotlib-base

test:
  imports:
    - stackview
    - stackview._image_widget
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/stackview
  summary: Interactive image stack viewing in jupyter notebooks based on ipycanvas and ipywidgets
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - haesleinhuepf
