{% set name = "stackview" %}
{% set version = "0.19.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/stackview-{{ version }}.tar.gz
  sha256: 3aef8dee10fc5882cdb8618e76f7652c53fbcc62a39fb0b952375bad2ffcb51f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy
    - python >={{ python_min }}
    - ipycanvas
    - ipywidgets
    - scikit-image
    - ipyevents
    - toolz
    - matplotlib-base
    - ipykernel
    - ipympl
    - wordcloud

test:
  imports:
    - stackview
    - stackview._image_widget
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/haesleinhuepf/stackview
  summary: Interactive image stack viewing in jupyter notebooks based on ipycanvas and ipywidgets
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - haesleinhuepf
