{% set name = "stackview" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stackview-{{ version }}.tar.gz
  sha256: b4a430da76576fd3725b2cb6b0b710a04373d217fd4403455d773a7c5404b8fb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numpy
    - python >=3.7
    - ipycanvas
    - ipywidgets
    - scikit-image
    - ipyevents
    - toolz
    - matplotlib-base
    - ipykernel

test:
  imports:
    - stackview
    - stackview._image_widget
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/stackview
  summary: Interactive image stack viewing in jupyter notebooks based on ipycanvas and ipywidgets
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - haesleinhuepf
