{% set name = "stackview" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/stackview-{{ version }}.tar.gz
  sha256: e93710366a37872c065d81c2f094be8489afbf9390764edf0a7b9d04be861d10

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy
    - python >={{ python_min }}
    - ipycanvas
    - ipywidgets
    - scikit-image
    - ipyevents
    - toolz
    - matplotlib-base
    - ipykernel
    - ipympl

test:
  imports:
    - stackview
    - stackview._image_widget
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/haesleinhuepf/stackview
  summary: Interactive image stack viewing in jupyter notebooks based on ipycanvas and ipywidgets
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - haesleinhuepf
